# pre-commit install --hook-type pre-commit --hook-type pre-push
repos:
- repo: local
  hooks:
      - id: julia-formatter
        name: "Julia Formatter"
        entry: "julia --project=. -e 'import JuliaFormatter: format; format(\".\", always_for_in=true, for_in_replacement=\"in\", remove_extra_newlines=true, import_to_using=true, pipe_to_function_call=true, format_docstrings=true, join_lines_based_on_source=true, indent_submodule=true,separate_kwargs_with_semicolon=true,format_markdown=true, whitespace_typedefs=false, whitespace_ops_in_indices=false)'"
        pass_filenames: false
        always_run: true
        language: "system"
      - id: tests
        name: "Run Tests"
        entry: "julia --project=. test/runtests.jl"
        pass_filenames: false
        always_run: true
        language: "system"